### ISSUE TITLE
Request: Support pgx VectorCodec string encoding

### ISSUE THREAD

**Issue by ohheydom** [pgvector/pgvector-go#16]
Hey there!

Just wondering if you'd be open to supporting pgx `VectorCodec` string encoding? We have a use-case where we're running a CopyFrom using a csv as a source, meaning that the rowSrc argument that gets passed into the `pgx.Tx.CopyFrom` contains all strings.

Currently we're getting the error -

```
ERROR: COPY from stdin failed: unable to encode \"[0.002...]\" into binary format for vector (OID 16576): cannot find encode plan (SQLSTATE 57014)
```

We wrote a custom implementation that works that looks like the following:

```go
func (VectorCodec) PlanEncode(_ *pgtype.Map, _ uint32, format int16, _ any) pgtype.EncodePlan {
	if format != pgx.BinaryFormatCode {
		return nil
	}

	return encodePlanVectorCodecBinary{}
}

func (encodePlanVectorCodecBinary) Encode(value any, buf []byte) ([]byte, error) {
	var vector pgvector.Vector

	switch v := value.(type) {
	case string:
		if err := vector.Parse(v); err != nil {
			return nil, err
		}
	case pgvector.Vector:
		vector = v
	default:
		return nil, fmt.Errorf("invalid encode type: %T", v)
	}

	return vector.EncodeBinary(buf)
}
```

Thank you for the great work on the library!

**Comment by ankane** [comment]
Hi @ohheydom, thanks for reporting! Addressed in the commit above (adding support for the text format to `PlanScan` handles it automatically).
