### ISSUE TITLE
pgvector.Vector vs. []float32

### ISSUE THREAD

**Issue by acim** [pgvector/pgvector-go#3]
What is the benefit of using `pgvector.Vector` type instead of directly using `[]float32` with pgx v5 driver? I haven't tried but it looks like  ` []float32` would work as well.

**Comment by ankane** [comment]
Hi @acim, `[]float32` already maps to the `real[]` Postgres type.

**Comment by acim** [comment]
But would []float work with database vector type?

**Comment by acim** [comment]
I can confirm this worked with pgx5.

**Comment by ankane** [comment]
It'll work in places where there's implicit conversion from `real[]` to `vector`, but not everywhere (remove `newVector` from the `SELECT` call in the tests to see).
