### ISSUE TITLE
Setting NULL Values / ERROR: vector must have at least 1 dimension

### ISSUE THREAD

**Issue by toadle** [pgvector/pgvector-go#7]
Hey everybody, 

I'm working on a product-matching algorithm and that has two phases: First aggregating data and then generating the embeddings. Also I have a big products database that I might need to generate embeddings for later. 

I'm using `pgvector-go` and `bun` to write the data. My model is defined like this:

```
type WapitiProduct struct {
	bun.BaseModel `bun:"table:products"`

	ID                             int64    `bun:"id,pk,type:int8,default:nextval('product_id_sequence')"`
	Name                           string
	NameEmbedding                  pgvector.Vector `bun:"type:vector(1536),nullzero"`
}
```

What I've noticed when using `pgvector-go` is that every entry always seems to be writing a vector to the database and I get an error like this: 

`ERROR: vector must have at least 1 dimension (SQLSTATE=22000)`

My guesses were that internal `bun` fails with it's `nullzero`-check on the new entry. And that seems to be correct, because this works:

```
type WapitiProduct struct {
	bun.BaseModel `bun:"table:products"`

	ID                             int64    `bun:"id,pk,type:int8,default:nextval('product_id_sequence')"`
	Name                           string
	NameEmbedding                  []float32 `bun:"array,nullzero,type:vector(1536)"`
}
```

But this ends up in a whole different mess, when really writing a 1536-entries vector.

I'm a bit unsure how to solve this. Is this a `bun` issue or a `pgvector`-thing?

**Comment by ankane** [comment]
Hi @toadle, for nullable fields, you can use:

```go
NameEmbedding *pgvector.Vector `bun:"type:vector(1536)"`
```
